version: "3.8"
services:
  mongodb:
    image: 'mongo'
    #define container name explicitly
    container_name: mongodb
    volumes:
      - data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: dennis
#      MONGO_INITDB_ROOT_PASSWORD: secret
    env_file:
      - ./env/mongo.env
  backend:
#    build: ./backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    #to keep the console open (-it)
    stdin_open: true
    tty: true
    depends_on:
      - backend

#named volumes must be indicated here
volumes:
  data:
  logs: